# Generated by Django 4.2.16 on 2026-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilemodel',
            name='image_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mediafilemodel',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
