# Generated by Django 4.2.16 on 2026-06-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_module', '0002_mediafilemodel_image_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilemodel',
            name='video_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
