# Generated by Django 4.2.16 on 2026-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_module', '0003_mediafilemodel_video_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilemodel',
            name='audio_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
