# Generated by Django 4.2.16 on 2026-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_module', '0004_mediafilemodel_audio_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilemodel',
            name='pdf_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
